import { jsPDF } from "jspdf";
import { BookMetadata, PageDefinition, BookDimensions } from "../types";

export const generatePDF = (metadata: BookMetadata, pages: PageDefinition[], dimensions: BookDimensions, coverImage?: string) => {
  // Create a new PDF document with custom dimensions
  const doc = new jsPDF({
    orientation: dimensions.width > dimensions.height ? "landscape" : "portrait",
    unit: dimensions.unit,
    format: [dimensions.width, dimensions.height]
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // KDP best practice margins (approx 0.5 - 0.75 inch)
  const margin = dimensions.unit === 'in' ? 0.6 : (dimensions.unit === 'px' ? 58 : 0.6);

  // Helper for consistent text positioning ratio
  const yPos = (percent: number) => pageHeight * percent;

  // --- Page 1: Belongs To Page ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("This coloring book", pageWidth / 2, yPos(0.35), { align: "center" });
  doc.text("belongs to:", pageWidth / 2, yPos(0.42), { align: "center" });
  
  const lineY = yPos(0.55);
  doc.setLineWidth(dimensions.unit === 'in' ? 0.02 : 2);
  doc.line(pageWidth * 0.2, lineY, pageWidth * 0.8, lineY);
  
  doc.setFontSize(10);
  doc.text("Generated by AI KDP Studio Professional", pageWidth / 2, pageHeight - margin, { align: "center" });

  // --- Page 2: Copyright & Meta ---
  doc.addPage();
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  let currentY = margin * 2;
  
  doc.text("Copyright © 2025. All Rights Reserved.", margin, currentY);
  currentY += dimensions.unit === 'in' ? 0.4 : 40;
  
  doc.setFont("helvetica", "bold");
  doc.text("Book Title:", margin, currentY);
  doc.setFont("helvetica", "normal");
  doc.text(metadata.title, margin + (dimensions.unit === 'in' ? 1.2 : 115), currentY);
  currentY += dimensions.unit === 'in' ? 0.3 : 30;

  doc.text("Interior created using AI KDP Studio generative engine.", margin, currentY);
  currentY += dimensions.unit === 'in' ? 0.3 : 30;
  doc.text("Amazon KDP Compatible Interior.", margin, currentY);

  // --- Optional Cover Page ---
  if (coverImage) {
      doc.addPage();
      doc.addImage(coverImage, "JPEG", 0, 0, pageWidth, pageHeight);
  }

  // --- Content Pages (KDP Professional Single-Sided) ---
  // In professional coloring books, we usually have a blank page on the left 
  // so coloring doesn't bleed through to the next drawing.
  pages.forEach((page, index) => {
    if (page.status === 'completed' && page.imageUrl) {
      // 1. Add Blank Page (to prevent bleed through in physical copy)
      doc.addPage();
      
      // 2. Add Main Drawing Page (Right Side)
      doc.addPage();
      
      const contentWidth = pageWidth - (margin * 2);
      
      // Calculate Image area
      const titleY = margin + (dimensions.unit === 'in' ? 0.2 : 20);
      const imageStartY = titleY + (dimensions.unit === 'in' ? 0.3 : 30);
      const availableHeight = pageHeight - (margin * 2) - imageStartY; 

      try {
        const imgProps = doc.getImageProperties(page.imageUrl);
        const imgRatio = imgProps.width / imgProps.height;
        
        let printWidth = contentWidth;
        let printHeight = contentWidth / imgRatio;

        if (printHeight > availableHeight) {
            printHeight = availableHeight;
            printWidth = printHeight * imgRatio;
        }

        const x = (pageWidth - printWidth) / 2;
        const y = imageStartY + (availableHeight - printHeight) / 2;

        doc.addImage(page.imageUrl, "PNG", x, y, printWidth, printHeight); 
      } catch (e) {
        doc.addImage(page.imageUrl, "PNG", margin, imageStartY, contentWidth, contentWidth * 1.3);
      }
      
      // Page number
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`${index + 1}`, pageWidth / 2, pageHeight - (margin/2), { align: "center" });
    }
  });

  // --- Last Page: Back Matter ---
  doc.addPage();
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Thank you for coloring!", pageWidth / 2, pageHeight / 2, { align: "center" });

  doc.save(`${metadata.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_interior_KDP.pdf`);
};