// @ts-nocheck
import { jsPDF } from "jspdf";
import { BookMetadata, PageDefinition, BookDimensions } from "../types";

/**
 * Generates a full KDP-ready interior PDF
 */
export const generatePDF = (metadata: BookMetadata, pages: PageDefinition[], dimensions: BookDimensions, coverImage?: string) => {
  const doc = new jsPDF({
    orientation: dimensions.width > dimensions.height ? "landscape" : "portrait",
    unit: dimensions.unit,
    format: [dimensions.width, dimensions.height]
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = dimensions.unit === 'in' ? 0.6 : 58;
  const yPos = (percent: number) => pageHeight * percent;

  // --- Page 1: Belongs To ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("This coloring book", pageWidth / 2, yPos(0.35), { align: "center" });
  doc.text("belongs to:", pageWidth / 2, yPos(0.42), { align: "center" });
  doc.line(pageWidth * 0.2, yPos(0.55), pageWidth * 0.8, yPos(0.55));
  doc.setFontSize(10);
  doc.text("Generated by AI KDP Studio Professional", pageWidth / 2, pageHeight - margin, { align: "center" });

  // --- Page 2: Copyright ---
  doc.addPage();
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Copyright © 2025. All Rights Reserved.", margin, margin * 2);
  doc.setFont("helvetica", "bold");
  doc.text("Book Title:", margin, margin * 2 + (dimensions.unit === 'in' ? 0.4 : 40));
  doc.setFont("helvetica", "normal");
  doc.text(metadata.title, margin + (dimensions.unit === 'in' ? 1.2 : 115), margin * 2 + (dimensions.unit === 'in' ? 0.4 : 40));

  // --- Optional Cover Page ---
  if (coverImage) {
      doc.addPage();
      doc.addImage(coverImage, "JPEG", 0, 0, pageWidth, pageHeight);
  }

  // --- Interior Pages (Single-Sided for KDP) ---
  pages.forEach((page, index) => {
    if (page.status === 'completed' && page.imageUrl) {
      doc.addPage(); // Blank back page
      doc.addPage(); // Main content page
      
      const contentWidth = pageWidth - (margin * 2);
      const titleY = margin + (dimensions.unit === 'in' ? 0.2 : 20);
      const imageStartY = titleY + (dimensions.unit === 'in' ? 0.3 : 30);
      const availableHeight = pageHeight - (margin * 2) - imageStartY; 

      try {
        const imgProps = doc.getImageProperties(page.imageUrl);
        const imgRatio = imgProps.width / imgProps.height;
        let printWidth = contentWidth;
        let printHeight = contentWidth / imgRatio;

        if (printHeight > availableHeight) {
            printHeight = availableHeight;
            printWidth = printHeight * imgRatio;
        }

        const x = (pageWidth - printWidth) / 2;
        const y = imageStartY + (availableHeight - printHeight) / 2;
        doc.addImage(page.imageUrl, "PNG", x, y, printWidth, printHeight); 
      } catch (e) {
        doc.addImage(page.imageUrl, "PNG", margin, imageStartY, contentWidth, contentWidth * 1.3);
      }
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`${index + 1}`, pageWidth / 2, pageHeight - (margin/2), { align: "center" });
    }
  });

  doc.addPage();
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Thank you for coloring!", pageWidth / 2, pageHeight / 2, { align: "center" });

  doc.save(`${metadata.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_full_KDP.pdf`);
};

/**
 * Generates a single-page PDF for one image
 */
export const generateSingleImagePDF = (imageUrl: string, title: string, dimensions: BookDimensions) => {
  const doc = new jsPDF({
    orientation: dimensions.width > dimensions.height ? "landscape" : "portrait",
    unit: dimensions.unit,
    format: [dimensions.width, dimensions.height]
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = dimensions.unit === 'in' ? 0.6 : 58;

  try {
    const imgProps = doc.getImageProperties(imageUrl);
    const imgRatio = imgProps.width / imgProps.height;
    const contentWidth = pageWidth - (margin * 2);
    const contentHeight = pageHeight - (margin * 2);
    
    let printWidth = contentWidth;
    let printHeight = contentWidth / imgRatio;

    if (printHeight > contentHeight) {
      printHeight = contentHeight;
      printWidth = printHeight * imgRatio;
    }

    const x = (pageWidth - printWidth) / 2;
    const y = (pageHeight - printHeight) / 2;

    doc.addImage(imageUrl, "PNG", x, y, printWidth, printHeight);
  } catch (e) {
    doc.addImage(imageUrl, "PNG", margin, margin, pageWidth - margin * 2, pageHeight - margin * 2);
  }

  doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_page.pdf`);
};